#ifndef COURSE_DB_TEST_H
#define COURSE_DB_TEST_H

#define UPDATE_COURSE_EXPECTED "Karl Was Here"

#define COURSE_CODE "CSCI 311"
#define INSTRUCTOR_NAME "Eli Selby"
#define EXPECTED_COURSE_ID 2004

#define ENROLLMENT_COURSE_ID 2004

#define COURSE_INFO_ID 2007

#endif 
